openapi: 3.0.0
info:
  title: Dialogue TTS Data Schema
  version: 1.0.0
  description: Data structure for Text-to-Speech (TTS) dialogue using the Web Speech API.

components:
  schemas:
    DialogueLine:
      type: object
      required:
        - speaker
        - text
      properties:
        speaker:
          type: string
          description: The name or role of the speaker. (Used to attempt matching specific voices)
          example: "Alice"
        text:
          type: string
          description: The dialogue content to be spoken aloud.
          example: "Hello, how are you today?"

    DialogueData:
      type: object
      required:
        - language_code
        - dialogue
      properties:
        language_code:
          type: string
          description: The BCP 47 language tag used for the entire dialogue (e.g., zh-TW, en-US, ja-JP).
          example: "en-US"
        dialogue:
          type: array
          description: An ordered array of dialogue lines.
          items:
            $ref: "#/components/schemas/DialogueLine"

paths: {} # This is a data structure schema, not an API definition.
