{
    "language_code": "en-US",
    "speakers": [
        {
            "name": "Sarah",
            "voice_hint": "Female"
        },
        {
            "name": "Michael",
            "voice_hint": "Male"
        }
    ],
    "dialogue": [
        {
            "speaker": "Sarah",
            "text": "I think we should launch the new product line next quarter."
        },
        {
            "speaker": "Michael",
            "text": "That sounds feasible, Sarah. Do we have all the marketing materials prepared?"
        },
        {
            "speaker": "Sarah",
            "text": "Not yet. I'm waiting for the final design approval from the creative team."
        }
    ]
}
